# Generated by Django 5.0.2 on 2024-09-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_firsttimer_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimer',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
