# Generated by Django 5.0.2 on 2024-09-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_firsttimer_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
