# Generated by Django 5.0.2 on 2024-09-11 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='base.country'),
        ),
    ]
