# Generated by Django 5.0.2 on 2024-09-11 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_firsttimer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimer',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='base.country'),
        ),
    ]
